package com.devtech.school_management_system.enums;

public enum SubjectCategory {
    JUNIOR_SECONDARY_LANGUAGES,
    JUNIOR_SECONDARY_ARTS,
    JUNIOR_SECONDARY_SCIENCES,
    O_LEVEL_LANGUAGES,
    O_LEVEL_ARTS,
    O_LEVEL_COMMERCIALS,
    O_LEVEL_SCIENCES,
    A_LEVEL_ARTS,
    A_LEVEL_COMMERCIALS,
    A_LEVEL_SCIENCES
}
